### PR TITLE
restore defang compose ls

### LINKED ISSUE #1831: regression: `defang compose ls` is gone
should relay to `defang ls`

### PR DESCRIPTION
**Pull request by jordanstephens**
## Description

Create an alias `defang compose ls` for the `defang ls` command.

## Linked Issues

* Fixes #1831

## Checklist

- [ ] I have performed a self-review of my code
- [ ] I have added appropriate tests
- [ ] I have updated the Defang CLI docs and/or README to reflect my changes, if necessary

## Summary by CodeRabbit

* **New Features**
  * Deployments command enhanced with an "ls" alias and added flags: --utc, --limit (-l) and --all (-a).

* **Bug Fixes**
  * Fixes initialization order so UTC mode and project settings are applied before listing deployments, preventing incorrect history listings.

### CODE REVIEW

File: src/cmd/cli/command/deployments.go [hunk 1]
```diff
@@ -6,41 +6,46 @@ import (
...
-			listType = defangv1.DeploymentType_DEPLOYMENT_TYPE_ACTIVE
-		}
-
-		if utc {
-			cli.EnableUTCMode()
-		}
+func makeDeploymentsCmd() *cobra.Command {
+	deploymentsCmd := &cobra.Command{
+		Use:         "deployments",
+		Aliases:     []string{"deployment", "deploys", "deps", "dep", "ls", "list"},
```
Comment (lionello) [inline src/cmd/cli/command/deployments.go]: To make sure help/docs show `compose ls`, we can get the main `use` commands from the caller:
```suggestion
func makeDeploymentsCmd(use string) *cobra.Command {
	deploymentsCmd := &cobra.Command{
Use:         use,
Aliases:     slices.Compact([]string{"deployments", use, "ls", "deployment", "deploys", "deps", "dep", "ls", "list"},
```
This uses `Compact` to avoid `deployments, deployments` or `ls, ls` in the help.

File: src/cmd/cli/command/commands.go [hunk 2]
```diff
@@ -292,9 +292,7 @@ func SetupCommands(version string) {
 	RootCmd.AddCommand(logsCmd)
 
 	// Deployments Command
-	deploymentsCmd.PersistentFlags().Bool("utc", false, "show logs in UTC timezone (ie. TZ=UTC)")
-	deploymentsCmd.PersistentFlags().Uint32P("limit", "l", 10, "maximum number of deployments to list")
-	deploymentsCmd.PersistentFlags().BoolP("all", "a", false, "show all deployments, including stopped")
+	var deploymentsCmd = makeDeploymentsCmd()
```
Comment (lionello) [inline src/cmd/cli/command/commands.go]:
```suggestion
	var deploymentsCmd = makeDeploymentsCmd("deployments")
```

File: src/cmd/cli/command/compose.go [hunk 3]
```diff
@@ -811,6 +811,8 @@ services:
 	composeCmd.AddCommand(makeComposeDownCmd())
 	composeCmd.AddCommand(makeComposePsCmd())
 	composeCmd.AddCommand(makeLogsCmd())
+	deploymentsCmd := makeDeploymentsCmd()
+	composeCmd.AddCommand(deploymentsCmd)
```
Comment (lionello) [inline src/cmd/cli/command/compose.go]:
```suggestion
	composeLsCmd := makeDeploymentsCmd("ls")
	composeCmd.AddCommand(composeLsCmd)
```
