### PR TITLE
Pass compose file issues to AI debugger

### LINKED ISSUE #922: Invoke AI debugger for Compose loader errors
## Description:

Pass compose loader errors to the AI debugger for help with compose authoring.

## Steps to reproduce the problem.
1. Use an invalid compose file:
  ```yaml
  services: [] # should be {}
  ```
2. `defang compose config`

## Expected behavior.
Should show "debug y/N?" prompt

## Actual behavior.
Quits with compose-go error.

## Environment:

- Defang Version (`defang version`):
- Operating system: (e.g., Windows, macOS, Linux)
- Shell (or Browser, if applicable):

### PR DESCRIPTION
**Pull request by nullfunc**
## Description

fixes #922 

On failure to load a compose file, because there are syntax or other issues, allow option to use AI Debugger to help assess the issue.

## Linked Issues
[#922](https://github.com/DefangLabs/defang/issues/922)

## Checklist

- [X] I have performed a self-review of my code
- [ ] I have added appropriate tests
- [ ] I have updated the Defang CLI docs and/or README to reflect my changes, if necessary

### CODE REVIEW

File: src/pkg/cli/debug.go [hunk 1]
```diff
@@ -59,8 +59,8 @@ func InteractiveDebug(ctx context.Context, c client.FabricClient, p client.Provi
 	return nil
 }
 
-func Debug(ctx context.Context, c client.FabricClient, p client.Provider, etag types.ETag, project *compose.Project, failedServices []string) error {
-	term.Debug("Invoking AI debugger for deployment", etag)
+func Debug(ctx context.Context, c client.FabricClient, p client.Provider, etag types.ETag, project *compose.Project, failedServices []string, termErr error) error {
```
Comment (lionello) [inline src/pkg/cli/debug.go:62]: stick to `loadError`

File: src/pkg/cli/debug.go [hunk 2]
```diff
@@ -74,10 +74,16 @@ func Debug(ctx context.Context, c client.FabricClient, p client.Provider, etag t
 		Services: failedServices,
 		Project:  project.Name,
 	}
-	err := p.Query(ctx, &req)
-	if err != nil {
-		return err
+
+	if etag != "" {
```
Comment (lionello) [inline src/pkg/cli/debug.go:78]: this can be a `switch-case` with a `default:` that panics or returns an error because there's nothing to debug.

File: src/pkg/cli/debug_test.go
Comment (lionello) [inline src/pkg/cli/debug_test.go:1]: Add a test for that last arg?

File: src/pkg/cli/compose/loader.go [hunk 3]
```diff
@@ -79,10 +79,7 @@ func (c *Loader) LoadProjectName(ctx context.Context) (string, error) {
 	return project.Name, nil
 }
 
-func (c *Loader) LoadProject(ctx context.Context) (*Project, error) {
-	if c.cached != nil {
-		return c.cached, nil
-	}
+func (c *Loader) LoadProjectOptions(ctx context.Context) (*cli.ProjectOptions, error) {
```
Comment (lionello) [inline src/pkg/cli/compose/loader.go:82]: This doesn't load so perhaps Get* is a better prefix. But tbh you're pretty much just using `newProjectOptions` as-is, so maybe just make that one public? Can `newProjectOptions` output logs? If so, we can move the `logrus` stuff into that func.

File: src/cmd/cli/command/compose.go [hunk 4]
```diff
@@ -63,17 +91,32 @@ func makeComposeUpCmd() *cobra.Command {
...
-			if err != nil {
+			project, loadErr := loader.LoadProject(ctx)
+			if loadErr != nil {
+				term.Warn(loadErr)
+				project, err := createCustomProject(ctx, loader)
+				if err != nil {
+					return err
+				}
+
+				if !nonInteractive {
```
Comment (lionello) [inline src/cmd/cli/command/compose.go:108]: No need to call `createCustomProject` when we're running non-interactively

File: src/cmd/cli/command/compose.go [hunk 5]
```diff
@@ -368,20 +411,42 @@ func makeComposeConfigCmd() *cobra.Command {
...
 		RunE: func(cmd *cobra.Command, args []string) error {
 			loader := configureLoader(cmd)
-			project, err := loader.LoadProject(cmd.Context())
-			if err != nil {
-				return err
+			ctx := cmd.Context()
+			project, loadErr := loader.LoadProject(ctx)
+			if loadErr != nil {
+				var err error
+				project, err = createCustomProject(ctx, loader)
```
Comment (lionello) [inline src/cmd/cli/command/compose.go:418]: ditto; only call this if non-interactive

File: src/cmd/cli/command/compose.go [hunk 6]
```diff
@@ -43,6 +45,32 @@ func splitManagedAndUnmanagedServices(serviceInfos compose.Services) ([]string,
...
+
+		projOpts.Name = filepath.Base(dir)
+	}
+	project := &compose.Project{
+		Name:        projOpts.Name,
+		WorkingDir:  projOpts.WorkingDir,
+		Environment: projOpts.Environment,
+	}
+
+	project.ComposeFiles = append(project.ComposeFiles, projOpts.ConfigPaths...)
```
Comment (lionello) [inline src/cmd/cli/command/compose.go:69]: move to literal

File: src/cmd/cli/command/compose.go [hunk 7]
```diff
@@ -43,6 +45,32 @@ func splitManagedAndUnmanagedServices(serviceInfos compose.Services) ([]string,
 	return managedServices, unmanagedServices
 }
 
+func createCustomProject(ctx context.Context, loader *compose.Loader) (*compose.Project, error) {
```
Comment (lionello) [inline src/cmd/cli/command/compose.go:48]: Bad name. This is for debugging.

**Review by lionello — CHANGES_REQUESTED** [review]

File: src/cmd/cli/command/compose.go (hunk 6 above)
Comment (nullfunc) [reply src/cmd/cli/command/compose.go:69]: :+1

File: src/cmd/cli/command/commands.go [hunk 8]
```diff
@@ -835,7 +835,7 @@ var debugCmd = &cobra.Command{
 			return err
 		}
 
-		return cli.Debug(cmd.Context(), client, provider, etag, project, args)
+		return cli.Debug(cmd.Context(), client, provider, etag, project, args, nil)
```
Comment (jordanstephens) [inline src/cmd/cli/command/commands.go:838]: this parameter list is getting a little long for my liking

File: src/cmd/cli/command/compose.go (hunk 4 above)
Comment (jordanstephens) [reply src/cmd/cli/command/compose.go:101]: Could we also invert these branches to avoid the double negative?
```go
				if nonInteractive {
					return err
				}

				// ...
```

File: src/cmd/cli/command/compose.go [hunk 9]
```diff
@@ -368,20 +410,38 @@ func makeComposeConfigCmd() *cobra.Command {
...
+
+				track.Evt("Debug Prompted", P("reason", loadErr))
+				// Call the AI debug endpoint using the original command context (not the tailCtx which is canceled)
+				if nil == cli.InteractiveDebug(ctx, client, provider, "", project, nil, loadErr) {
+					return nil // don't show the defang hint if debugging was successful
+				}
 			}
-			return nil
+
+			return loadErr
```
Comment (jordanstephens) [inline src/cmd/cli/command/compose.go:444]: Isn't `loadErr` guaranteed to be `nil` here?
```suggestion
			return  nil
```

File: src/cmd/cli/command/compose.go [hunk 10]
```diff
@@ -368,20 +410,38 @@ func makeComposeConfigCmd() *cobra.Command {
...
+				if !nonInteractive {
+					project, err = CreateDebugProject(loader)
+					if err != nil {
+						return err
+					}
+				}
+
+				track.Evt("Debug Prompted", P("reason", loadErr))
+				// Call the AI debug endpoint using the original command context (not the tailCtx which is canceled)
+				if nil == cli.InteractiveDebug(ctx, client, provider, "", project, nil, loadErr) {
```
Comment (jordanstephens) [inline src/cmd/cli/command/compose.go:439]: What is `project` here if we're in a non-interactive shell?

File: src/cmd/cli/command/compose.go [hunk 11]
```diff
@@ -368,20 +410,38 @@ func makeComposeConfigCmd() *cobra.Command {
...
+					return nil
+				}
+
+				loadErr = err
 			}
 
-			if _, _, err := cli.ComposeUp(cmd.Context(), project, client, provider, compose.UploadModeIgnore, defangv1.DeploymentMode_UNSPECIFIED_MODE); !errors.Is(err, cli.ErrDryRun) {
-				return err
+			if loadErr != nil {
+				if !nonInteractive {
```
Comment (jordanstephens) [inline src/cmd/cli/command/compose.go:430]: I'd like to avoid this double-negative, if we can. What is meant to happen if the shell is non-interactive? Should we just return?

File: src/pkg/cli/debug.go [hunk 12]
```diff
@@ -59,8 +59,8 @@ func InteractiveDebug(ctx context.Context, c client.FabricClient, p client.Provi
 	return nil
 }
 
-func Debug(ctx context.Context, c client.FabricClient, p client.Provider, etag types.ETag, project *compose.Project, failedServices []string) error {
-	term.Debug("Invoking AI debugger for deployment", etag)
+func Debug(ctx context.Context, c client.FabricClient, p client.Provider, etag types.ETag, project *compose.Project, failedServices []string, loadErr error) error {
```
Comment (jordanstephens) [inline src/pkg/cli/debug.go:62]: I think boolean parameters are a code smell. Rather than add one here, what do you think about creating a new function `DebugDeployment` and another `DebugLoadError`. Then we can have each prepare a `DebugRequest` which is appropriate and the caller can decide which to call based on the parameter.

File: src/pkg/cli/debug_test.go [hunk 13]
```diff
@@ -64,17 +65,42 @@ func TestQueryHasProject(t *testing.T) {
...
+		t.Errorf("expected no error, got %v", err)
+	}
+
+	if err := Debug(context.Background(), fabricClient, provider, "", project, []string{"service"}, nil); err != nil {
+		if err.Error() == "no information to use for debugger" {
+			return
+		}
+	}
+
+	t.Error("expected error, got none")
```
Comment (lionello) [inline src/pkg/cli/debug_test.go:105]: little odd to have this outside of the `if`, will make it cumbersome when we add tests later:
```suggestion
	t.Run("without load error", func(t *testing.T) {
		err := Debug(context.Background(), fabricClient, provider, "", project, []string{"service"}, nil)
		if err == nil {
			t.Fatal("expected error, got none")
		}
		if err.Error() != "no information to use for debugger" {
			t.Error("expected: no information to use for debugger")
		}
	})
```

File: src/pkg/cli/debug_test.go [hunk 14]
```diff
@@ -64,17 +65,42 @@ func TestQueryHasProject(t *testing.T) {
...
+		ComposeFiles: []string{"composefile"},
+	}
+
+	loadErr := errors.New("load error")
+	provider := MustHaveProjectNameQueryProvider{}
+	fabricClient := MockDebugFabricClient{}
+
+	if err := Debug(context.Background(), fabricClient, provider, "etag", project, []string{"service"}, loadErr); err != nil {
+		t.Errorf("expected no error, got %v", err)
+	}
```
Comment (lionello) [inline src/pkg/cli/debug_test.go:97]:
```suggestion
	t.Run("with load error", func(t *testing.T) {
		if err := Debug(context.Background(), fabricClient, provider, "etag", project, []string{"service"}, loadErr); err != nil {
			t.Errorf("expected no error, got %v", err)
		}
	})
```

**Review by lionello — APPROVED** [review]

File: src/pkg/cli/debug.go (hunk 12 above)
Comment (nullfunc) [reply src/pkg/cli/debug.go:62]: It's an actual error object with the load error text inside.

File: src/cmd/cli/command/compose.go (hunk 9 above)
Comment (nullfunc) [reply src/cmd/cli/command/compose.go:444]: if it's not interactive then we don't process the loadErr through the AI Debugger

File: src/cmd/cli/command/compose.go (hunk 10 above)
Comment (nullfunc) [reply src/cmd/cli/command/compose.go:439]: it contains things like workdir, the compose file, env variables, etc... stuff the AI Debugger can chew on.

File: src/pkg/cli/debug.go (hunk 12 above)
Comment (jordanstephens) [reply src/pkg/cli/debug.go:62]: You're right. I misspoke. I think this is called a ["flag argument"](https://martinfowler.com/bliki/FlagArgument.html) where a function takes one branch if a parameter is present and another if that parameter is not present. A "boolean parameter" is a special case of a "flag argument."

I stand by my comment though. We can relieve `Debug` of the responsibility of having to know about how to query deployment logs _and_ unpack this error object if we split them up. Then we can test them separately, and the length of our parameter list can be kept more moderate.

File: src/cmd/cli/command/compose.go (hunk 10 above)
Comment (jordanstephens) [reply src/cmd/cli/command/compose.go:439]: I think `project` is `nil` in the case that `loadErr != nil && nonInteractive`

Comment (jordanstephens) [reply src/cmd/cli/command/compose.go:439]: What do you think about flattening these conditions a bit, like this?
```go
project, loadErr := loader.LoadProject(ctx)
if loadErr == nil {
	_, _, err = cli.ComposeUp(ctx, project, client, provider, compose.UploadModeIgnore, defangv1.DeploymentMode_UNSPECIFIED_MODE)
	if err != nil && errors.Is(err, cli.ErrDryRun) {
		return nil
	}

	loadErr = err
}

if loadErr != nil {
	if nonInteractive {
		return loadErr
	}

	project, err = CreateDebugProject(loader)
	if err != nil {
		return err
	}
}

track.Evt("Debug Prompted", P("reason", loadErr))
// Call the AI debug endpoint using the original command context (not the tailCtx which is canceled)
if nil == cli.InteractiveDebug(ctx, client, provider, "", project, nil, loadErr) {
	return nil // don't show the defang hint if debugging was successful
}

return nil
```

File: src/pkg/cli/debug.go [hunk 15]
```diff
@@ -74,15 +81,59 @@ func Debug(ctx context.Context, c client.FabricClient, p client.Provider, etag t
...
+	// for _, request := range resp.Requests {
+	// 	term.Info(request)
+	// }
+	return nil
+}
+
+func DebugComposeFileLoadError(ctx context.Context, c client.FabricClient, p client.Provider, project *compose.Project, loadErr error) error {
+	term.Debug("Invoking AI debugger for Load Error")
+
+	files := findMatchingProjectFiles(project, nil)
```
Comment (jordanstephens) [inline src/pkg/cli/debug.go:110]: No point in doing a bunch of file IO if one of the exit conditions are met, so I think we should check those before looking for matching files.

```
	term.Debug("Invoking AI debugger for Load Error")
	if DoDryRun {
		return ErrDryRun
	}

	if loadErr == nil {
		return errors.New("no information to use for debugger")
	}

	req := defangv1.DebugRequest{
		Files:   files := findMatchingProjectFiles(project, nil),
		Project: project.Name,
		Logs: loadErr.Error()
	}

	resp, err := c.Debug(ctx, &req)
```

File: src/pkg/cli/debug.go [hunk 16]
```diff
@@ -74,15 +81,59 @@ func Debug(ctx context.Context, c client.FabricClient, p client.Provider, etag t
...
-	err := p.Query(ctx, &req)
+
+	if etag != "" {
+		err := p.Query(ctx, &req)
+		if err != nil {
+			return err
+		}
+	} else {
+		return errors.New("no information to use for debugger")
+	}
```
Comment (jordanstephens) [inline src/pkg/cli/debug.go:92]: Nit pick, but you can flatten this
```suggestion
	if etag == "" {
		return errors.New("no information to use for debugger")
	}

	err := p.Query(ctx, &req)
	if err != nil {
		return err
	}
```

File: src/pkg/cli/debug.go [hunk 17]
```diff
@@ -42,9 +42,16 @@ func InteractiveDebug(ctx context.Context, c client.FabricClient, p client.Provi
...
+		if err := DebugComposeFileLoadError(ctx, c, p, project, loadError); err != nil {
+			term.Warnf("Failed to debug compose file load: %v", err)
+			return err
+		}
+	} else {
+		if err := DebugDeployment(ctx, c, p, etag, project, failedServices); err != nil {
+			term.Warnf("Failed to debug deployment: %v", err)
+			return err
+		}
 	}
```
Comment (jordanstephens) [inline src/pkg/cli/debug.go:55]: Love this. Thank you!

**Review by jordanstephens — APPROVED** [review]
A couple more small suggestions, but I trust you
