### PR TITLE
Lio/fix default stack

### LINKED ISSUE #1824: Stacks warning: using env var when it's not using it

### PR DESCRIPTION
**Pull request by lionello**
## Linked Issues

* Fixes #1824

## Checklist

- [x] I have performed a self-review of my code
- [ ] I have added appropriate tests
- [ ] I have updated the Defang CLI docs and/or README to reflect my changes, if necessary

## Summary by CodeRabbit

* **Refactor**
  * Unified stack selection and retrieval for sessions and stack manager flows
  * Streamlined stack manager initialization and session loader behavior

* **New Features**
  * Server-provided default stack is now returned instead of an error
  * Tail and debug flows now include and respect the active stack name

* **Bug Fixes**
  * Consistent handling of project/stack resolution across commands and previews

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

**Comment by jordanstephens** [comment]
I sorted out the config set issue. It's because I was trying to use an aws provider in the test. I changed it to use the defang provider, since we already have a mock fabric set up.

File: src/cmd/cli/command/compose.go [hunk 1]
```diff
@@ -394,14 +394,15 @@ func handleTailAndMonitorErr(ctx context.Context, err error, debugger *debug.Deb
 		// Call the AI debug endpoint using the original command context (not the tail ctx which is canceled)
 		if nil != debugger.DebugDeploymentError(ctx, debugConfig, errDeploymentFailed) {
 			// don't show this defang hint if debugging was successful
-			tailOptions := newTailOptionsForDeploy(debugConfig.Deployment, debugConfig.Since, true)
+			tailOptions := newTailOptionsForDeploy("", debugConfig.Deployment, debugConfig.Since, true)
```
Comment (lionello) [inline src/cmd/cli/command/compose.go]: @jordanstephens this could use stack name here `""`
