### PR TITLE
Nonexistent project error fix

### LINKED ISSUE #483: defang new some_non_existent_project show no error
from the CLI when trying to create a project from an non-existent sample it asks for project name and opens vscode but no files are created.

Expected: If a sample does not exist an error should be shown to the user and no project directory created.

### PR DESCRIPTION
**Pull request by Chrisyhjiang**
Currently when trying to create a project from an non-existent sample it asks for project name and opens vscode but no files are created.

Closes #483

### CODE REVIEW

**Review by lionello — APPROVED** [review]

File: src/cmd/cli/command/commands.go [hunk 1]
```diff
@@ -510,6 +509,17 @@ Generate will write files in the current folder. You can edit them and then depl
 
 		if sample != "" {
 			qs = qs[1:] // user picked a sample, so we skip the description question
+			sampleExists := false
+			for _, s := range sampleList {
```
Comment (lionello) [inline src/cmd/cli/command/commands.go:513]: Use helpers from the `slices` package

File: src/pkg/cli/new.go [hunk 2]
```diff
@@ -97,9 +101,11 @@ func InitFromSamples(ctx context.Context, dir string, names []string) error {
 			}
 		}
 	}
+	if !sampleFound {
+		return fmt.Errorf("sample not found")
+	}
 	return nil
 }
-
```
Comment (lionello) [inline src/pkg/cli/new.go:102]: removed this empty line?

File: src/pkg/cli/new.go [hunk 3]
```diff
@@ -97,9 +101,11 @@ func InitFromSamples(ctx context.Context, dir string, names []string) error {
 			}
 		}
 	}
+	if !sampleFound {
+		return fmt.Errorf("sample not found")
```
Comment (lionello) [inline src/pkg/cli/new.go:105]: make this a global variable `var ErrSampleNotFound = errors.New("sample not found")` and use it here as well as in commands.go

File: src/cmd/cli/command/commands.go [hunk 4]
```diff
@@ -438,7 +438,7 @@ var generateCmd = &cobra.Command{
 			}
 			return cli.InitFromSamples(cmd.Context(), "", []string{sample})
 		}
-
+		sampleList, cachedErr := cli.FetchSamples(cmd.Context())
```
Comment (lionello) [inline src/cmd/cli/command/commands.go:441]: better name for the err?

**Review by lionello — CHANGES_REQUESTED** [review]

File: src/pkg/cli/new_test.go [hunk 5]
```diff
@@ -0,0 +1,16 @@
...
+	"context"
+	"testing"
+)
+
+func TestInitFromSamples(t *testing.T) {
+	err := InitFromSamples(context.Background(), t.TempDir(), []string{"nonexisting"})
+	if err == nil {
+		t.Fatal("Expected test to fail")
+	}
+	if err.Error() != "sample not found" {
```
Comment (lionello) [inline src/pkg/cli/new_test.go:13]: you can actually improve this test now by using `errors.Is(err, …)` to ensure it returns the new var

**Review by lionello — APPROVED** [review]
