### PR TITLE
`defang --provider aws` shows improved error if unauthenticated

### LINKED ISSUE #782: `defang --provider aws` should fail fast if unauthenticated
Running `defang up --provider aws` takes 15s to fail if I am not authenticated:
```
defang up --provider aws
 ! AWS provider was selected, but AWS environment variables are not set
 * Using AWS provider
 * Compressing build context for app at /Users/jordan/wk/welcome-to-defang/app
 * Uploading build context for app
Error: operation error CloudFormation: UpdateStack, get identity: get credentials: failed to refresh cached credentials, process provider error: error in credential_process: exit status 253
failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, exceeded maximum number of attempts, 3, request send failed, Get "http://169.254.169.254/latest/meta-data/iam/security-credentials/": dial tcp 169.254.169.254:80: connect: host is down
Could not authenticate to the AWS service. Please check your aws credentials and try again.
```

Ideally, we should:

- [x]  fail more quickly, earlier
- [x]  print instructions on how to authenticate inline, or at least link to docs.

### PR DESCRIPTION
**Pull request by commit111**
Fixes #782

When running `defang up --provider=aws` without authenticating to AWS first:
- Error will now fail earlier, specifically before  the `* Packaging...` and `* Uploading...` steps
- Error will now link to the docs: `AWS credentials must be set (https://docs.defang.io/docs/providers/aws#getting-started)`

Details:
- `NewByocProvider()` returns two values (`*ByocAws, error`) instead of one (`*ByocAws`) to deal with error sooner
   - Checks `AccountInfo()` to verify whether user is logged into their AWS account
   - Returns `ErrMissingAwsCreds` wrapped error when user's AWS credentials cannot be verified
   - Unit tests and integration tests are adjusted for this change 

- Also some DigitalOcean fixes:
   -  Error will now link to docs if DigitalOcean token is not set:  `DIGITALOCEAN_TOKEN must be set (https://docs.defang.io/docs/providers/digitalocean#getting-started)`
   - `byocProvider` variable renamed to `doProvider` for the DigitalOcean case in `connect.go` file

### CODE REVIEW

**Review by nullfunc — APPROVED** [review]

File: src/pkg/cli/client/byoc/aws/byoc_integration_test.go [hunk 1]
```diff
@@ -15,7 +16,13 @@ import (
 var ctx = context.Background()
 
 func TestDeploy(t *testing.T) {
-	b := NewByocClient(ctx, client.GrpcClient{}, "ten ant") // no domain
+	origRegion := os.Getenv("AWS_REGION")
+	os.Setenv("AWS_REGION", "us-west-2")
+	defer func() { os.Setenv("AWS_REGION", origRegion) }()
```
Comment (lionello) [inline src/pkg/cli/client/byoc/aws/byoc_integration_test.go:21]:
```suggestion
	t.Setenv("AWS_REGION", "us-west-2")
```

Comment (commit111) [reply src/pkg/cli/client/byoc/aws/byoc_integration_test.go]: Ok I've updated it!

**Review by lionello — CHANGES_REQUESTED** [review]
`AWS_REGION` is optional because the user might have it set in their `~/.aws/config`

File: src/pkg/cli/client/byoc/aws/byoc_test.go [hunk 2]
```diff
@@ -44,12 +48,20 @@ func TestDomainMultipleProjectSupport(t *testing.T) {
 		{"Project1", "tenant1", "web", port80, "web--80.project1.example.com", "web.project1.example.com", "web.project1.internal"},
 		{"Tenant2", "tenant1", "web", port80, "web--80.tenant2.example.com", "web.tenant2.example.com", "web.tenant2.internal"},
 		{"tenant1", "tenAnt1", "web", port80, "web--80.example.com", "web.example.com", "web.tenant1.internal"},
+		{"tenant1", "tenant1", "web", port80, "web--80.example.com", "web.example.com", "web.tenant1.internal"},
```
Comment (lionello) [inline src/pkg/cli/client/byoc/aws/byoc_test.go:51]: same as previous?

File: src/pkg/cli/client/byoc/aws/byoc_integration_test.go [hunk 3]
```diff
@@ -15,7 +16,12 @@ import (
 var ctx = context.Background()
 
 func TestDeploy(t *testing.T) {
-	b := NewByocProvider(ctx, client.GrpcClient{}, "ten ant") // no domain
+	b, err := NewByocProvider(ctx, client.GrpcClient{}, "ten ant") // no domain
+	if err != nil {
```
Comment (lionello) [inline src/pkg/cli/client/byoc/aws/byoc_integration_test.go:20]: since this file is tagged as `integration`, we should expect credentials to be available so we should ensure we get `nil`

File: src/pkg/cli/client/byoc/aws/byoc.go [hunk 4]
```diff
@@ -63,13 +63,20 @@ type ByocAws struct {
...
+func NewByocProvider(ctx context.Context, grpcClient client.GrpcClient, tenantId types.TenantID) (*ByocAws, error) {
 	b := &ByocAws{
 		cdTasks: make(map[string]ecs.TaskArn),
 		driver:  cfn.New(byoc.CdTaskPrefix, aws.Region("")), // default region
 	}
 	b.ByocBaseClient = byoc.NewByocBaseClient(ctx, grpcClient, tenantId, b)
-	return b
+
+	_, err := b.AccountInfo(ctx)
+	if err != nil {
```
Comment (lionello) [inline src/pkg/cli/client/byoc/aws/byoc.go:76]: are all errors related to missing credentials?

Comment (commit111) [reply src/pkg/cli/client/byoc/aws/byoc.go:76]: yes, but we can wrap the err to preserve it, which will probably be a better practice

File: src/pkg/cli/client/byoc/aws/byoc_test.go (hunk 2 above)
Comment (commit111) [reply src/pkg/cli/client/byoc/aws/byoc_test.go:51]: small difference in "tenAnt1" and "tenant1"

File: src/pkg/cli/client/byoc/aws/byoc_integration_test.go (hunk 3 above)
Comment (commit111) [reply src/pkg/cli/client/byoc/aws/byoc_integration_test.go:20]: right, we will do t.Skip() if the error is an "unauthorized" error, and t.Fatal() when it is anything other than that.

**Review by lionello — APPROVED** [review]
LGTM! @commit111 please resolve conflicts with `main`; @edwardrf can help.
