### PR TITLE
fix: don't write file outside of refered project dir

### LINKED ISSUE #1912: CLI writes stack file outside of project
When trying to clean-up a project, I ran this locally in the defang-mvp folder. It ended up writing a stack file in that folder, which is not really what I needed/expected. In fact, I was doing a down, so why bother writing a file at all?

```sh
$ export DEFANG_PROVIDER=aws
$ AWS_REGION=us-west-2 defang down --detach --project-name crewai --stack one click
 * Stack "oneclick" loaded and saved to "/Users/llunesu/dev/defang-mvp/.defang/oneclick". Add this file to source control
 * Using the "oneclick" stack on aws from --stack flag and previous deployment
 * Running CD command "destroy" in project "crewai"
 * Waiting for CloudFormation stack defang-cd to be updated...
 * Deleted services, deployment ID 76b5bcb13b104224abb1abcd0233d7ff
 ! Stored project configs are not deleted.
```

### PR DESCRIPTION
**Pull request by lionello**
## Description

There's been situations where I use `defang -f ~/somefoldersomewhere/compose.yaml --stack=foo up` or `defang down --project-name=crewai --stack=oneclick` and the CLI ends up writing a stack file in my current folder. Added a unit test to repro, then fixed it.

## Linked Issues

Fixes #1912 

## Checklist

- [x] I have performed a self-review of my code
- [x] I have added appropriate tests
- [ ] I have updated the Defang CLI docs and/or README to reflect my changes, if necessary

## Summary by CodeRabbit

* **Refactor**
  * Improved project directory resolution with enhanced fallback handling for configuration file discovery.
  * Added `WithPath` option to customize compose file lookup paths.

* **Tests**
  * Enhanced test coverage for project directory resolution scenarios outside standard project structures.

### CODE REVIEW

File: src/cmd/cli/command/compose.go [hunk 1]
```diff
@@ -98,15 +98,17 @@ func makeComposeUpCmd() *cobra.Command {
 			} else if accountInfo, err := session.Provider.AccountInfo(ctx); err != nil {
 				term.Debugf("AccountInfo failed: %v", err)
 			} else if len(resp.Deployments) > 0 {
-				confirmed, err := confirmDeployment(session.Loader.TargetDirectory(ctx), resp.Deployments, accountInfo, session.Provider.GetStackName())
+				workingDir, _ := session.Loader.ProjectWorkingDir(ctx)
```
Comment (lionello) [inline src/cmd/cli/command/compose.go]: Renamed TargetDirectory -> ProjectWorkingDir and now returns err.

File: src/cmd/cli/command/session_test.go [hunk 2]
```diff
@@ -49,20 +50,56 @@ func TestNewStackManagerForCommand(t *testing.T) {
...
+			expectedTarget: "..",
+		},
+		{
+			name:           "outside a project directory - refer to compose file in child",
+			directory:      ".",
+			paths:          []string{"without-stack/compose.yaml"},
+			expectedTarget: "without-stack",
+		},
+		{
+			name:           "outside a project directory - refer to compose file in sibling",
```
Comment (lionello) [inline src/cmd/cli/command/session_test.go]: this is the case that would fail w/ old code
