### PR TITLE
Fix for defang upgrade

### LINKED ISSUE #658: Defang upgrade showing incorrect info
I'm running in a devcontainer which installs using the install script. When I run `defang upgrade` (just noticed it existed), I get the wrong upgrade instructions:

```
vscode ➜ /workspaces/samples/samples/django-channels-redis (django-channels) $ defang upgrade
 * To upgrade defang, run the following command:

 brew upgrade defang
vscode ➜ /workspaces/samples/samples/django-channels-redis (django-channels) $ whereis defang 
defang: /usr/local/bin/defang /home/vscode/.local/bin/defang
```

### PR DESCRIPTION
**Pull request by lionello**
Fixes #658

If you don't have `brew`, it would check whether the executable has the brew prefix `""` which is always true.

### CODE REVIEW

File: src/pkg/cli/upgrade.go [hunk 1]
```diff
@@ -24,7 +25,7 @@ func Upgrade(ctx context.Context) error {
 	}
 	term.Debugf(" - Evaluated: %s\n", ex)
 
-	if strings.HasPrefix(ex, homebrewPrefix(ctx)) {
+	if prefix, err := homebrewPrefix(ctx); err == nil && strings.HasPrefix(ex, prefix) {
```
Comment (jordanstephens) [inline src/pkg/cli/upgrade.go:28]: this is a lot for one line imo
```suggestion
	prefix, err := homebrewPrefix(ctx)
	if err == nil && strings.HasPrefix(ex, prefix) {
```

**Review by jordanstephens — APPROVED** [review]

File: src/pkg/cli/upgrade.go (hunk 1 above)
Comment (lionello) [reply src/pkg/cli/upgrade.go:28]: True. I did it like that to limit the scope of the variables.
